version: "3.7"

# docker-compose up -d
# https://github.com/localstack/localstack
# https://hub.docker.com/r/localstack/localstack
# https://dev.to/goodidea/how-to-fake-aws-locally-with-localstack-27me
# http://localhost:4572/
# http://localhost:8055/#!/infra
services:
  s3-localstack:
    image: localstack/localstack:0.10.6
    container_name: s3-localstack-demo
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - '.volumes/localstack:/tmp/localstack'
    networks:
      - food4u-network

  db-mysql:
    image: mysql:8.0.18
    container_name: db-mysql-demo
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=food4u
      - MYSQL_USER=food4u
      - MYSQL_PASSWORD=food4u
    volumes:
      - '.volumes/db-mysql:/var/lib/mysql'
    networks:
      - food4u-network


networks:
  food4u-network:
    driver: bridge