create table if not exists configuration
(
   -- id          bigint generated by default as identity,
    key         varchar(100)        not null,
    value       text                not null,
    -- Auditing
    version     bigint              not null,
    created_at  timestamp           not null default now(),
    modified_at timestamp           not null,
    created_by  text                not null,
    modified_by text                not null,

    constraint pk_configuration primary key (key)
    --constraint uk_configuration_key unique (key)
    );

COMMENT ON TABLE configuration IS 'Settings used for business logic';
--comment on column configuration.id is 'The primary key';
comment on column configuration.key is 'The configuration key';
comment on column configuration.value is 'The configuration value';
comment on column configuration.version is 'The version number of the row';
comment on column configuration.created_at is 'Timestamp of the row creation';
comment on column configuration.modified_at is 'Timestamp of the last row update';
comment on column configuration.created_by is 'Application user that has created the row';
comment on column configuration.modified_by is 'Application user that has updated the row';