server:
  compression:
    enabled: true
  port: 8080
  shutdown: graceful
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: sgoa-service-sb3
  # Time to wait for active requests to finish during the shutdown
  lifecycle:
    timeout-per-shutdown-phase: 20s

  output:
    ansi:
      enabled: always # log output with colors

  mvc:
    problemdetails:
      enabled: true

  cloud:
    function:
      ## those are the declaration of the listeners
      definition: deployBpmResponse;receiveExternalTaskLoadOperation;receiveExternalTaskLoadSingleOperation
    stream:

      bindings:
        ## producers
        subscribeTopics:
          destination: bpm.subscribe.worker
          producer:
            required-groups:
              - backup
        deployBpm:
          destination: bpm.deploy.workflow
          producer:
            required-groups:
              - backup
        correlateMessage:
          destination: bpm.correlate.message
          producer:
            required-groups:
              - backup
        startProcess:
          destination: bpm.start.process
          producer:
            required-groups:
              - backup


        ## consumers
        deployBpmResponse:
          destination: bpm.deploy.workflow.response
          group: ${spring.application.name}
        receiveExternalTaskLoadOperation:
          destination: bpm.notify.externaltask
          group: ${config.bpm.topic.LoadOperation}
        receiveExternalTaskLoadSingleOperation:
          destination: bpm.notify.externaltask
          group: ${config.bpm.topic.LoadSingleOperation}



        deployBpmResponse-in-0:
          content-type: application/json
          destination: bpm.deploy.workflow.response
          group: ${spring.application.name}
          consumer:
            concurrency: 1
            max-attempts: 10
            back-off-initial-interval: 150
            back-off-multiplier: 2.0
            back-off-max-interval: 20000

        receiveExternalTaskLoadOperation-in-0:
          content-type: application/json
          destination: bpm.notify.externaltask
          group: ${config.bpm.topic.LoadOperation}
          consumer:
            concurrency: 1
            max-attempts: 10
            back-off-initial-interval: 150
            back-off-multiplier: 2.0
            back-off-max-interval: 20000
        receiveExternalTaskLoadSingleOperation-in-0:
          content-type: application/json
          destination: bpm.notify.externaltask
          group: ${config.bpm.topic.LoadSingleOperation}
          consumer:
            concurrency: 1
            max-attempts: 10
            back-off-initial-interval: 150
            back-off-multiplier: 2.0
            back-off-max-interval: 20000

      rabbit:
        bindings:
          # producers
          subscribeTopics:
            producer:
              ttl: 1296000000
              lazy: true
              exchange-type: fanout
          deployBpm:
            producer:
              ttl: 1296000000
              lazy: true
              exchange-type: fanout
          correlateMessage:
            producer:
              ttl: 1296000000
              lazy: true
              exchange-type: fanout
          startProcess:
            producer:
              ttl: 1296000000
              lazy: true
              exchange-type: fanout


          # consumers
          deployBpmResponse-in-0:
            consumer:
              consumer-tag-prefix: ${spring.application.name}.deployBpmResponse
              acknowledge-mode: auto
              #auto-bind-dlq: true
              prefetch: 1
              #prefetch: 3
              #dlq-quorum:
              #  enabled: true
              quorum:
                enabled: true
          receiveExternalTaskLoadOperation-in-0:
            consumer:
              consumer-tag-prefix: ${spring.application.name}.receiveExternalTaskLoadOperation
              binding-routing-key: ${config.bpm.topic.LoadOperation}
              acknowledge-mode: auto
              auto-bind-dlq: true
              prefetch: 1
              dlq-quorum:
                enabled: true
              quorum:
                enabled: true
          receiveExternalTaskLoadSingleOperation-in-0:
            consumer:
              consumer-tag-prefix: ${spring.application.name}.receiveExternalTaskLoadSingleOperation
              binding-routing-key: ${config.bpm.topic.LoadSingleOperation}
              acknowledge-mode: auto
              auto-bind-dlq: true
              prefetch: 1
              dlq-quorum:
                enabled: true
              quorum:
                enabled: true



# spring.data.elasticsearch.properties.index.search.slowlog.threshold.query.info=1ms

# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  elasticsearch:
    host-and-port: "localhost:9200"
    path-prefix: ""
    reverse-proxy: false
    https: false
    secured: false
    username: "user"
    password: "--"
    customers-index: customers

logging:
  level:
    root: info
    org:
      springframework:
        web: DEBUG
        data:
          elasticsearch:
            core: debug
            client: trace
        boot:
          autoconfigure:
            logging: INFO
      apache.http: debug
    io:
      github.jlmc: DEBUG


# logging.level.org.apache.http=DEBUG

# logging.level.org.springframework.data.elasticsearch.client.WIRE=trace


config:
  workerId: ${spring.application.name}
  messaging:
    routingExpression: type
  bpm:
    deploy:
      enableDuplicateFilter: true
      deployChangedOnly: true
      migrate: true
    topic:
      LoadOperation: sgoa_LoadOperation
      LoadSingleOperation: sgoa_LoadSingleOperation
    subscribeTopics:
      - ${config.bpm.topic.LoadOperation}
      - ${config.bpm.topic.LoadSingleOperation}