spring:
  application:
    name: rx-items
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://admin:admin@localhost:27017/admin

---
spring:
  config:
    activate:
      on-profile: default
  data:
    mongodb:
      username: "admin"
      password: "admin"
      database: "local"

  autoconfigure:
    exclude: de.flapdoodle.embed.mongo.spring.autoconfigure.EmbeddedMongoAutoConfiguration

---
spring:
  config:
    activate:
      on-profile: mongodb-container-test
  autoconfigure:
    exclude: de.flapdoodle.embed.mongo.spring.autoconfigure.EmbeddedMongoAutoConfiguration


---
spring:
  config:
    activate:
      on-profile: mongodb-embedded-test

