#version: '3.4'

services:
  mongo:
    image: mongo:4.4.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - .volumes/mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  #localhost:59146