drop table if exists todos;

create table todos
(
    id          int8 generated by default as identity,
    created     timestamp,
    description varchar(1500) not null,
    title       varchar(100)  not null,
    updated     timestamp,
    version     int8,
    primary key (id)
)
