#spring.application.name=order-management-service

spring:
  application:
    name: order-management-service

  mvc:
    log-request-details: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 10000
      auto-commit: false
      schema: pizza_condo_oms_db
  jpa:
    properties:
      hibernate:
        connection:
          autocommit: false
        generate_statistics: true
        format_sql: true
        default_schema: ${spring.datasource.hikari.schema}
        order_updates: true
        query:
          in_clause_parameter_padding: true
          plan_cache_max_size: 4096
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0.0.0_0
    default-schema: ${spring.datasource.hikari.schema}
    validate-migration-naming: true

## could
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          flightFinished-out-0:
            producer:
              #topic: order-events,order-received-events

              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        flightFinished-out-0:
          destination: order-received-events









###   cloud.stream:
#    function.definition: planeArrivedProcessor;flightArrivedConsumer
#    kafka:
#      bindings:
#        planeArrivedProcessor-in-0:
#          consumer:
#            enableDlq: true
#            dlqName: plane-arrived-dlq-v1
#        flightArrivedConsumer-in-0:
#          consumer:
#            enableDlq: true
#            dlqName: flight-arrived-dlq-v1
#        planeArrivedProcessor-out-0:
#          producer.configuration:
#            key.serializer: org.apache.kafka.common.serialization.StringSerializer
#    bindings:
#      planeArrivedProcessor-in-0:
#        destination: plane-arrived-v1
#        group: flight-api
#        consumer:
#          retryable-exceptions:
#            com.henriquels25.flightapi.plane.infra.stream.NoFlightFoundException: false
#      planeArrivedProcessor-out-0:
#        destination: flight-arrived-v1
#      flightArrivedConsumer-in-0:
#        destination: flight-arrived-v1
#        group: flight-api
#      flightFinished-out-0:
#        destination: flight-finished-v1



###
# logging
logging:
  level:
    root: info
    io:
      github:
        jlmc: debug
    org:
      springframework:
        web: debug
      hibernate: info
      hibernate.SQL: debug
      hibernate.type.descriptor.sql: trace
      hibernate.type.descriptor.sql.BasicBinder: trace
      hibernate.type.descriptor.sql.BasicExtractor: trace
      hibernate.engine.transaction.internal.TransactionImpl: debug
      hibernate.engine.jdbc.batch: debug
      hibernate.stat: debug
      hibernate.SQL_SLOW: info
      hibernate.orm.jdbc.bind: trace
      hibernate.orm.jdbc.extract: trace
      flywaydb: debug
    com:
      zaxxer.hikari: debug


