spring:
  application:
    name: orders-api
  profiles:
    active: local

  jackson:
    constructor-detector: default
    property-naming-strategy: LOWER_CAMEL_CASE
    # ignore null properties in the serialization, similar to @JsonInclude(JsonInclude.Include.NON_NULL)
    default-property-inclusion: non_null
    deserialization:
      # Throw an exception if an unknown propriety arrives in the request body, the default value is false
      fail-on-unknown-properties: true
      # throw an exception if a property annotated with @JsonIgnore arrives in the request body, the default value is false
      fail-on-ignored-properties: true
    serialization:
      fail-on-empty-beans: true
      fail-on-self-references: true
      indent-output: true

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      # this only works when we don't have any static resource for example some website
      add-mappings: false

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      # key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap-servers: localhost:9092

logging:
  level:
    root: info
    org.springframework: debug
    io.github.jlmc: debug

---
spring:
  config:
    activate:
      on-profile: dev
  kafka:
    producer:
      bootstrap-servers: kafka-dev1:9092,kafka-dev2:9092,kafka-dev3:9092
      # key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer



---
spring:
  config:
    activate:
      on-profile: prod

  kafka:
    producer:
      bootstrap-servers: kafka1:9092,kafka2:9092,kafka3:9092
      # key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

