server:
  port: 8081

io:
  xine:
    auth-servers-with-jwt:
      keystore:
        path: keystores/example.jks
        password: 654321
        keypair-alias: example

spring:
  datasource:
    url: jdbc:h2:mem:authtestdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      maximum-pool-size: 2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
