server:
  port: 8081

io:
  xine:
    auth-servers-with-jwt:
      keystore:
        path: keystores/example.jks
        password: 654321
        keypair-alias: example

spring:
  datasource:
    # url: jdbc:h2:mem:authtestdb
    url: jdbc:h2:./security-auth-servers-with-jwt/auth-servers-with-jwt/db/authtestdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
    hikari:
      maximum-pool-size: 2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
        ## In a JPA-based app, you can choose to let Hibernate create the schema or use schema.sql,
        ## but you cannot do both. Make sure to disable spring.jpa.hibernate.ddl-auto if you use schema.sql.
      ddl-auto: none
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      # springframework.jdbc.core.JdbcTemplate: DEBUG # log only sql statement
      springframework.jdbc.core: TRACE # log sql statement and parameters
