drop table if exists t_permission cascade;
drop table if exists t_user cascade;
drop table if exists t_user_group cascade;
drop table if exists t_user_group_permission cascade;
drop table if exists t_user_user_group cascade;

drop table if exists oauth_client_details cascade;

create table t_permission
(
    id          integer generated by default as identity,
    description varchar(255),
    name        varchar(255),
    primary key (id)
);

create table t_user
(
    id              integer generated by default as identity,
    email           varchar(255) not null,
    name            varchar(255) not null,
    pw              varchar(255) not null,
    registration_at datetime(6)  not null,
    primary key (id)
);

create table t_user_group
(
    id   integer generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table t_user_group_permission
(
    user_group_id integer not null,
    permission_id integer not null,
    primary key (user_group_id, permission_id)
);

create table t_user_user_group
(
    user_id       integer not null,
    user_group_id integer not null,
    primary key (user_id, user_group_id)
);

alter table t_user_group_permission
    add constraint FKjba33cdukt6li1mytdnbgr835
        foreign key (permission_id)
            references t_permission;

alter table t_user_group_permission
    add constraint FKc9jci780x6v12heu6r75nvh1v
        foreign key (user_group_id)
            references t_user_group;

alter table t_user_user_group
    add constraint FKh1y26a3sl1nqfhwhk79tf6rwx
        foreign key (user_group_id)
            references t_user_group;

alter table t_user_user_group
    add constraint FK4u3ly6hewdk7prbhn4b3plh02
        foreign key (user_id)
            references t_user;


create table oauth_client_details
(
    client_id               varchar(255),
    resource_ids            varchar(256),
    client_secret           varchar(256),
    scope                   varchar(256),
    authorized_grant_types  varchar(256),
    web_server_redirect_uri varchar(256),
    authorities             varchar(256),
    access_token_validity   integer,
    refresh_token_validity  integer,
    additional_information  varchar(4096),
    autoapprove             varchar(256),

    primary key (client_id)
);