#spring.application.name=openfeign-resilient-customisations
spring:
  application:
    name: openfeign-resilient-customisations

  mvc:
    problemdetails:
      enabled: true

  cloud:
    openfeign:
      lazy-attributes-resolution: true # If you need the attributes to be resolved lazily, set the spring.cloud.openfeign.lazy-attributes-resolution property value to true. Tip: For Spring Cloud Contract test integration, lazy attribute resolution should be used.
      client:
        config:
          products-service-client:
            url: http://localhost:8089
            #retryer: io.github.jlmc.poc.adapters.ProductsServiceClientRetryer
            connect-timeout: 15000
            read-timeout: 15000
            logger-level: full
            #dismiss404: false
            follow-redirects: true

            micrometer:
              enabled: false
          order-id-generator-service-client:
            url: http://localhost:8089
            #retryer: io.github.jlmc.poc.adapters.ProductsServiceClientRetryer
            connect-timeout: 15000
            read-timeout: 15000
            logger-level: full
            #dismiss404: false
            follow-redirects: true

            micrometer:
              enabled: false


logging:
  level:
    io.github.jlmc: debug
    org:
      springframework:
        web: debug
        cloud:
          openfeign: debug


poc:
  orders-id:
    type: REMOTE